#' A regression output object
#' 
#' Objects of class\code{LinearOuput} are created by the \code{RegRun} function
#' 
#' 
#' An object of the class 'LMOutput' has the following slots:
#' \itemize{
#' \item \code{coef} A matrix of coefficient estimates generated by the regressions of all possible variable combinations
#' \item \code{R2} A vector of R-squared values generated by the regressions of all possible variable combinations
#' }
#' 
#' @author Dino Hadzic \email{dino.hadzic@@wustl.edu}
#' @aliases LinearOutput-class initialize,LinearOutput-method getcoef,RegRun-method getR2,LinearOutput-method
#' @rdname LinearOutput
#' @export
setClass(Class="LinearOutput",
         representation = representation(
           coef = "matrix",
           R2 = "numeric"
           ),
         prototype = prototype(
           coef = matrix(),
           R2 = numeric()
           )
)

#' @export
setMethod("initialize", "LinearOutput",
          function(.Object, ...){
            value=callNextMethod()
            return(value)
          }
)

#' @export
setGeneric("getcoef",
           function(object="LinearOutput"){
             standardGeneric("getcoef")
           }
)

#' @export
setMethod("getcoef", "LinearOutput",
          function(object){
            return(object@coef)
          }
)

#' @export
setGeneric("getR2",
           function(object="LinearOutput") {
             standardGeneric("getR2")
           }
)

#' @export 
setMethod("getR2", "LinearOutput",
          function(object){
            return(object@R2)
          }
)









