#' Runs regressions on all possible combinations of covariates
#' 
#' Generates the coefficients and R-squared values on all possible combinations of covariates
#' 
#' @param M A matrix of cases for the covariates
#' @param Y A numeric vector that whose length is equal to the number of rows as \code{M}
#' 
#' @return An object of class LinearOuput 
#'  \item{coef}{A matrix of coefficient estimates generated by the regressions of all possible variable combinations}
#'  \item{R2}{A vector of R-squared values generated by the regressions of all possible variable combinations}
#'  @author Dino Hadzic \email{dino.hadzic@@wustl.edu}
#'  @examples
#'  
#'  exM <- matrix(rnorm(30), ncol=3)
#'  exY <- c(rnorm(10))
#'  RegRun(exM, exY)
#'  @seealso \code{\link{RegRunSig}}
#'  @rdname RegRun
#'  @aliases RegRun,ANY-method
#'  @export
setGeneric(name="RegRun",
           def=function(M, Y, ...)
             {standardGeneric("RegRun")}
)

#' @export
setMethod(f="RegRun",
          definition=function(M, Y, ...){
            R2s <- numeric()
            coefs <- matrix(NA, nrow=ncol(M)+1)
            for(i in 1:ncol(M)){
              combos <- combn(1:ncol(M), i)
              for(j in 1:ncol(combos)){
                lm1 <- numeric(ncol(M) + 1)
                lm1[c(1, combos[,j]+1)] <- lm(Y ~ M[,combos[,j]])[["coefficients"]]
                R2s <- c(R2s, summary(lm(Y ~ M[,combos[,j]]))[["r.squared"]])   
                coefs <- cbind(coefs, lm1)
              }
            }
            colnames(coefs)[-1] <- paste("Reg", 1:ncol(coefs))
            rownames(coefs) <- paste("Coeff", 0:(nrow(coefs)-1))
            return(new("LinearOutput", coef=coefs[,-1], R2=R2s))
          }
)
