#' Subclass of regression output object and coefficients of sorted significance
#' 
#' Objects of class \code{LinearOutputSig} are created by the \code{RegRunSig} function
#' 
#' 
#' An object of the class LinearOutputSig' has the following slots:
#' \itemize{
#' \item \code{coef} A matrix of coefficient estimates generated by the regressions of all possible variable combinations
#' \item \code{R2} A vector of R-squared values generated by the regressions of all possible variable combinations
#' \item \code{Sig} A vector of character elements representing the sorted significance of coefficient estimates
#' }
#' 
#' @author Dino Hadzic \email{dino.hadzic@@wustl.edu}
#' @aliases LinearOutputSig-class initialize,LinearOutputSig-method getcoef,RegRunSig-method getR2,LinearOutputSig-method getSig,LinearOutputSig-method
#' @rdname LinearOutputSig
#' @export
setClass(Class="LinearOutputSig",
         contains="LinearOutput",
         representation = representation(
           Sig = "character"
           ),
         prototype = prototype(
           coef = matrix(),
           R2 = numeric(),
           Sig = character()
           )
)

#' @export
setMethod("initialize", "LinearOutputSig",
          function(.Object, ...){
            value=callNextMethod()
            return(value)
          }
)

#' @export
setGeneric("getSig",
           function(object="LinearOutputSig"){
             standardGeneric("getSig")
           }
)


#' @export
setMethod("getSig", "LinearOutputSig",
          function(object){
            return(object@Sig)
          }
)

